#!/bin/sh
# /etc/init.d/redis
# sudo chmod +x /etc/init.d/redis
#nginx 启动脚本
#ubuntu 14.04平台
#zs测试可用
#学习shell编程; 部分自己编写,逻辑可能不够紧密; 2015-06-11
#weimob

#Configurationsinjected by install_server below....
#EXEC=/usr/local/redis/bin/redis-server
#CLIEXEC=/usr/local/redis/bin/redis-cli
EXEC=/usr/local/bin/redis-server
CLIEXEC=/usr/local/bin/redis-cli
PIDFILE=/var/run/redis.pid
#CONF="/usr/local/redis/etc/redis.conf"
CONF="/etc/redis.conf"
REDISPORT="6379"
NAME="redis-server"
###############
# SysVInit Information
#chkconfig: - 58 74
#description: redis_6379 is the redis daemon.
###BEGIN INIT INFO
#Provides: redis_6379
#Required-Start: $network $local_fs $remote_fs
#Required-Stop: $network $local_fs $remote_fs
#Default-Start: 2 3 4 5
#Default-Stop: 0 1 6
#Should-Start: $syslog $named
#Should-Stop: $syslog $named
#Short-Description: start and stop redis_6379
#Description: Redis daemon
### ENDINIT INFO


case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
            echo "$PIDFILE exists, processis already running or crashed"
        else
            echo "Starting Redisserver..."
            PID=`ps -ef|grep $REDISPORT |grep -v grep |awk '{print $2}'`
            touch $PIDFILE |cat ${PID} >> $PIDFILE
            #chown redis:redis $PIDFILE
            $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
            echo "$PIDFILE does not exist,process is not running"
        else
            PID=$(cat $PIDFILE)
            echo "Stopping ..."
            $CLIEXEC -p $REDISPORT shutdown
            while [ -x /proc/${PID} ]
            do
               echo "Waiting for Redis toshutdown ..."
               sleep 1
            done
            echo "Redis stopped"
        fi
        ;;
    status)
        if [ ! -f $PIDFILE ]
        then
            echo "$PIDFILE does not exist,process is not running"
        else
            PID=$(cat $PIDFILE)
            echo "Redis is running($PID)"
        fi
        ;;

        #PID=$(cat $PIDFILE)
        #if [ ! -x /proc/${PID} ]
        #then
        #    echo 'Redis is not running'
        #else
        #    echo "Redis is running($PID)"
        #fi
        #;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Please use start, stop,restart or status as first argument"
        ;;
esac
